[providers]
python = "3.11"

[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
nixLibs = ["zlib", "libjpeg", "libpng"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "cd backend",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
